/* Lista de productos*/
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "controlarStock", "fechaCreacion", "estado") VALUES (1, 'Frances', 1, 0, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (2, 'Pan de dulce', 1, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (3, 'Tostado', 1, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "controlarStock", "fechaCreacion", "estado") VALUES (4, 'Pirujito', 1, 0, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "controlarStock", "fechaCreacion", "estado") VALUES (5, 'Baguett', 1, 0, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "controlarStock", "fechaCreacion", "estado") VALUES (6, 'Pan de agua', 1, 0, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "controlarStock", "fechaCreacion", "estado") VALUES (7, 'Pirujo grande', 1, 0, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "controlarStock", "fechaCreacion", "estado") VALUES (8, 'Pirujo Integral', 1, 0, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (9, 'Pan dulce grande', 1, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (10, 'Galleta', 1, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "controlarStock", "fechaCreacion", "estado") VALUES (11, 'Lenguas', 1, 0, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (12, 'Magdalena', 2, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (13, 'Magdalena 2 sab', 2, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (14, 'Zepelin', 2, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (15, 'Zepelin 2 sab', 2, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (16, 'Zepelin zanahoria', 2, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (17, 'Golden', 2, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (18, 'Pan de banano', 2, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (19, 'Muffin', 2, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (20, 'Muffin chocolate', 2, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (21, 'Muffin zanahoria', 2, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (22, 'Donas', 2, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (23, 'Donas con azucar', 2, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (24, 'Bolas', 2, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (25, 'Submarinos', 2, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (26, 'Tostado empacado', 2, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (27, 'Palito empacado', 2, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (28, 'Abiscochado', 2, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (29, 'Empanizado', 2, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (30, 'Choco chips', 2, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (31, 'Polvorosas', 2, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (32, 'Polvorones', 2, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (33, 'Miga libra', 2, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (34, 'Miga 1/2 libra', 2, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (35, 'Golden porcion', 2, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (36, 'Tarta', 2, '2025-02-14', 'A');
INSERT INTO productos ("idProducto", "nombreProducto", "idCategoria", "fechaCreacion", "estado") VALUES (37, 'Donas de nutella', 2, '2025-02-14', 'A');

/*-----------------Asignar precios a los productos--------------------------------------------*/
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (1, 1, 3, 1, 0.3333333333333333, '2025-01-31', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (2, 2, 3, 1, 0.3333333333333333, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (3, 3, 3, 1, 0.3333333333333333, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (4, 4, 3, 1, 0.3333333333333333, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (5, 5, 1, 1, 1, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (6, 6, 1, 1, 1, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (7, 7, 1, 1, 1, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (8, 8, 1, 1, 1, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (9, 9, 1, 1, 1, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (10, 10, 1, 1, 1, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (11, 11, 1, 1, 1, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (12, 12, 1, 23, 23, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (13, 13, 1, 23, 23, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (14, 14, 1, 18, 18, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (15, 15, 1, 18, 18, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (16, 16, 1, 25, 25, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (17, 17, 1, 20, 20, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (18, 18, 1, 20, 20, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (19, 19, 1, 3, 3, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (20, 20, 1, 4, 4, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (21, 21, 1, 5, 5, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (22, 22, 1, 3, 3, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (23, 23, 1, 2.5, 2.5, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (24, 24, 1, 3.5, 3.5, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (25, 25, 1, 3.5, 3.5, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (26, 26, 1, 5, 5, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (27, 27, 1, 5, 5, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (28, 28, 1, 2.5, 2.5, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (29, 29, 1, 2.5, 2.5, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (30, 30, 1, 3, 3, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (31, 31, 1, 1.25, 1.25, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (32, 32, 1, 0.5, 0.5, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (33, 33, 1, 5, 5, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (34, 34, 1, 2.5, 2.5, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (35, 35, 1, 3.5, 3.5, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (36, 36, 1, 5, 5, '2025-02-14', NULL);
INSERT INTO precios ("idPrecio", "idProducto", "cantidad", "precio", "precioPorUnidad", "fechaInicio", "fechaFin") VALUES (37, 37, 1, 5, 5, '2025-02-14', NULL);

