DROP TABLE IF EXISTS GASTOSDIARIOS;
DROP TABLE IF EXISTS GASTOSDIARIOSDETALLES;

CREATE TABLE IF NOT EXISTS GASTOSDIARIOS (
    idGastoDiario INTEGER PRIMARY KEY AUTOINCREMENT,
    idVenta INTEGER,
    idUsuario INTEGER,
    montoTotalGasto DECIMAL(10, 2) NOT NULL,
    fechaIngreso DATETIME,
    estado TEXT NOT NULL CHECK(estado IN ('A', 'N')) DEFAULT 'A',
    FOREIGN KEY (idVenta) REFERENCES VENTAS(idVenta) ON DELETE CASCADE,
    FOREIGN KEY (idUsuario) REFERENCES USUARIOS(idUsuario)
); 

CREATE TABLE IF NOT EXISTS GASTOSDIARIOSDETALLES (
    idGastoDiarioDetalle INTEGER PRIMARY KEY AUTOINCREMENT,
    idGastoDiario INTEGER,
    detalleGasto TEXT,
    subtotal DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (idGastoDiario) REFERENCES GASTOSDIARIOS(idGastoDiario) ON DELETE CASCADE
);

    
    
    